### PR TITLE
Fix default mappings unmapping

### PR DESCRIPTION
**Pull request by backdround**
There is a problem with unmapping default extension keys.  
Example:
```lua
mappings = {
  i = {
    ["<M-m>"] = false,
  },
},
```
will end up with something like this eventually:
```lua
mappings = {
  i = {
    ["<M-m>"] = false,
    ["<A-m>"] = fb_actions.move,
  },
},
```
I didn't retrieved all the results, that depend on which mapping will be proceeded first, but my experience is that I have my global mapping muted (it doesn't work and the default mapping doesn't work either)

So I've rewritten part with mappings merging. Current algorithm:
- retrieves all ignored mappings (in internal termcodes)
- merges all mappings
- removes all ignored mappings (comparing with internal termcodes)

### CODE REVIEW

**Comment by jamestrew** [comment]
Sorry for the late response.
I'm not sure how to feel about this. The current behavior seems to be consistent with telescope's builtin pickers.
```lua
require("telescope").setup({
  defaults = {
    mappings = {
      i = {
        ["<A-m>"] = false,
      },
    },
  },
  pickers = {
    find_files = {
      mappings = {
        i = {
          ["<M-m>"] = function() print("hello") end,
        },
      },
    },
  },
})
```
I think if we were to implement a change like this, it should probably be in upstream telescope.
What do you think?

**Comment by backdround** [comment]
I've just tested it with telescope's mappings, and telescope's mappings work as expected with `<A-m>` and `<M-m>` either.

My original problem was that I tried to disable all of the plugin's mappings and I didn't figure out how I can do this.

for `telescope` for example, I can simply use `default_mappings = {}`:
```lua
telescope.setup({
  defaults = {
    default_mappings = {},
  },
})
```

Unfortunately, this plugin doesn't support this approach.

**Comment by jamestrew** [comment]
Ah okay. For disabling default mappings see https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/322#issuecomment-1793981447

**Comment by backdround** [comment]
Thanks. I did it at the time of the pull request.

It it isn't required, I'll close it

**Pull request closed without merging**
