### PR TITLE
Fix path_display for browser - fixes #177

### LINKED ISSUE #177: 'path_display' telescope opt doesn't work properly with the file-browser
### Description

_W

### Neovim version

```markdown
NVIM v0.8.0-dev-1000-gc0050b71e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by inferno@InfernoPC

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### Operating system and version

Artix Linux

### Steps to reproduce

nvim -u minimal_conf.lua

### Expected behavior

To have only one slash at the end "/"

### Actual behavior

Instead it has two slashes at the end "//" 

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
local layout = require('telescope.actions.layout')
local previewers = require("telescope.previewers")
local sorters = require("telescope.sorters")
_G.load_config = function()
  require('telescope').setup({
	defaults = {
		vimgrep_arguments = {
			"rg",
			"--color=never",
			"--no-heading",
			"--with-filename",
			"--line-number",
			"--column",
			"--smart-case",
		},
		prompt_prefix = ":: ",
		selection_caret = "> ",
		entry_prefix = "  ",
		initial_mode = "insert",
		selection_strategy = "reset",
		sorting_strategy = "descending",
		layout_strategy = "horizontal",
		layout_config = {
			horizontal = {
				mirror = false,
				height = 20,
			},
			vertical = {
				mirror = false,
				width = 0.5
			},
		},
		file_sorter = sorters.get_fuzzy_file,
		file_ignore_patterns = {},
		generic_sorter = sorters.get_generic_fuzzy_sorter,
		winblend = 10,
		border = {},
		borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
		color_devicons = true,
		use_less = true,
		path_display = { "smart" },
		-- set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
		file_previewer = previewers.vim_buffer_cat.new,
		grep_previewer = previewers.vim_buffer_vimgrep.new,
		qflist_previewer = previewers.vim_buffer_qflist.new,
		mappings = {
			i = {
				["<C-]>"] = layout.toggle_preview,
				-- ["<C-]>"] = layout.cycle_layout_next,
			},
		}

		-- Developer configurations: Not meant for general override
		-- buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
	},
	extensions = {
		file_browser = {
			hijack_netrw = true,
		},
		fzf = {
			fuzzy = true, -- false will only do exact matching
			override_generic_sorter = true, -- override the generic sorter
			override_file_sorter = true, -- override the file sorter
			case_mode = "smart_case", -- or "ignore_case" or "respect_case"
			-- the default case_mode is "smart_case"
		},
	},
	["ui-select"] = {
		require("telescope.themes").get_dropdown({
			-- even more opts
		}),
	},
	pickers = {
		find_files = {
			find_command = {
				"fd",
				"--type",
				"f",
				"--strip-cwd-prefix",
				"-E",
				"*cache*"
			},
		},
	},
})
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by vignesh0025**
Remove use of utils.transform_path() for displaying the entry in the file-browser. Since we are displaying only the current folder content, we need not respect the path_display option set in telescope.nvim

### CODE REVIEW

**Comment by vignesh0025** [comment]
fixes #177

**Review by fdschmidt93 — COMMENTED** [review]
Thanks!

I'm afraid it's not that easy. At least two scenarios should strictly speaking allow `path_display` to be set.

1. `file_browser`: for whenever `depth > 1`
2. `folder_browser`

Would you be happy to also fix it for those cases as part of this PR? That would be very much appreciated!

**Comment by vignesh0025** [comment]
> Thanks for the PR!
> 
> While looking fine at first glance for the simple case, I'm afraid it's not that easy. At least two scenarios should strictly speaking allow `path_display` to be set.
> 
> 1. `file_browser`: for whenever `depth > 1`
> 2. `folder_browser`
> 
> Would you be happy to also fix it for those cases as part of this PR? That would be very much appreciated!

1. folder_depth seems to be working as expected. I am not seeing wierd output. 
2. Can show please show some screenshot for how depth>1 is supposed to look like ? Will try to implement it.

**Comment by fdschmidt93** [comment]
This should be fixed by #208. Please let me know otherwise :)

**Pull request closed without merging**
