### PR TITLE
fix: keymapping defaults and overrides

### PR DESCRIPTION
**Pull request by fdschmidt93**
* Consistent default keymappings between insert and normal mode
* Fix being unable to fully override (unmap) default keymappings

This partially solves #5 as now mappings can be fully unmapped and overriden at telescope setup. What's still not possible is unmapping when called interactively eg

```lua
require "telescope".extensions.file_browser.file_browser {
  attach_mappings = function(prompt_bufnr, map)
    map("i", "<C-f>", false)
    return true
  end
}
```
which seems to be an upstream issue.

In any case, I prefer having the default configuration in `pconf` and it should largely fix the issue.

@j-hui could you please test whether this works for you? Many thanks in advance!

### CODE REVIEW

**Comment by j-hui** [comment]
@fdschmidt93 I'm on this branch and it doesn't seem to be working for me. I'm currently testing with:

```lua
    require'telescope'.setup {
      extensions = {
        file_browser = {
          mappings = {
            i = {
              ['<C-f>'] = function () print("C-f overriden") end,
            }
          },
        },
      },
    }
```

Is there something I should be doing differently to remap `<C-f>`?

**Comment by fdschmidt93** [comment]
I checked your snippet and it works as intended for me.

> My vimrc setup is a bit of an over-engineered mess with callbacks out the wazoo, but all the telescope-specific mappings are being set using the mappings mechanism that it provides. (Though I'm not really sure if that's the right thing to do.)

I think this is a "access" order issue. In brief, order should be

setup (the above) -> `require("telescope").load_extension "file_browser"` *actually loads the config) -> everything else

Before I go on a wild goose chase, this is setup as intended? :sweat_smile:

Another way to validate would be: keep just the setup and load, unmap the file browser and try this from cmdline

`require "telescope".extensions.file_browser.file_browser()`

----

On this PR itself, I'll have to check https://github.com/nvim-telescope/telescope.nvim/pull/1473 which cleans up mappings a lot upstream

**Comment by ikerurda** [comment]
Hi!
I'm not able to overwrite mappings either.
Currently I have a similar config to the following:
```lua
local tl = require "telescope"
local fb_actions = require"telescope".extensions.file_browser.actions
local actions = require"telescope.actions"

tl.setup {
  extensions = {
    file_browser = {
      theme = "ivy",
      layout_config = {height = .5},
      mappings = {
        i = {["<C-v>"] = fb_actions.move_file, ["<C-x>"] = fb_actions.remove_file, ["<C-d>"] = actions.preview_scrolling_down}
      }
    }
  }
}
tl.load_extension "file_browser"
```
Even when trying it from the commandline, as you suggested, I only get the plugin with that `theme` and `layout_config` when `mappings = {...}` and `local fb_actions = ...` are removed

**Comment by fdschmidt93** [comment]
Ah, I've just realized what the issue most likely is.

You guys do `local fb_actions = require"telescope".extensions.file_browser.actions` and thereby access the extension de facto before it has been set up. Then, the picker config table never gets properly created and forwarded onto the picker from `require "telescope".extensions.file_browser.file_browser` because the setup is called on the first access onto the extension.

I think this is something we might have to fix upstream. Right now this can be fixed by wrapping the action into another function, such that `fb_actions` will be required lazily or via hot-reloading through plenary.

```lua

if pcall(require, "plenary") then
  R = function(name)
    require("plenary.reload").reload_module(name)
    return require(name)
  end
end
```

and then you'd map

`["key"] = R "telescope".extensions.file_browser.actions`

I'll try to look into it some time next week.

**Comment by j-hui** [comment]
> setup (the above) -> require("telescope").load_extension "file_browser" *actually loads the config) -> everything else

Yeah, this is the verbatim lua snippet I use to set things up:

```lua
    local fb_actions = require 'telescope'.extensions.file_browser.actions
    local imaps = {
      ['<C-a>'] = { '<Home>',   type = 'command' },
      ['<C-e>'] = { '<End>',    type = 'command' },
      ['<C-f>'] = { '<Right>',  type = 'command' },
      ['<C-b>'] = { '<Left>',   type = 'command' },
      ['<C-h>'] = { '<BS>',     type = 'command' },
      ['<C-k>'] = function () vim.cmd 'norm! d$' end,
      ['<Esc>'] = require'telescope.actions'.close,
      ['<C-c>'] = { '<Esc>',    type = 'command' },
      ["<C-e>"] = function() print("test") end, -- successfully overrides
    }
    require'telescope'.setup {
      defaults = { mappings = { i = imaps } },
      extensions = {
        file_browser = {
          mappings = {
            i = {
              ['<C-f>'] = function () print("C-f overriden") end, -- doesn't work
            }
            -- vim.tbl_extend('force', imaps, {
            --   -- ['<C-j>'] = fb_actions.create_file,
            --   ['<C-j>'] = function () print("c-j") end,
            --   ['<C-v>'] = fb_actions.toggle_browser,
            -- })
          },
        },
      },
    }
  require'telescope'.load_extension 'file_browser'
```

I'm not sure if tihs is related to requiring `fb_actions` early though, because I'm not even able to override `<C-f>` with a regular function that does not depend on `fb_actions`.

This is also true when I check out `apply_mappings_fixup`.

**Comment by fdschmidt93** [comment]
Yes, it's because require fb_actions is on the top.

> because I'm not even able to override <C-f> with a regular function that does not depend on fb_actions.

That doesnt do anything because you index the extensions table via requiring fb_actions.

You need to wrap every reference to in a function like

`[key] = function(prompt_bufnr) fb_action.remove_file(prompt_bufnr) end`

or hot reloading as mentioned above.

Sorry, typing from mobile.

**Comment by j-hui** [comment]
ahhh I see what you mean. This works:

```lua
    local function fb_action(f)
      return function (b)
        require'telescope'.extensions.file_browser.actions[f](b)
      end
    end
    local imaps = {
      -- same as before
    }
    require'telescope'.setup {
      defaults = { mappings = { i = imaps } },
      extensions = {
        file_browser = {
          mappings = {
            i = vim.tbl_extend('force', imaps, {
              ['<C-j>'] = fb_action 'create_file',
              ['<C-v>'] = fb_action 'toggle_browser',
            }),
          },
        },
      },
    }
    require'telescope'.load_extension 'file_browser'
```

**Comment by fdschmidt93** [comment]
> The definition of fb_action is a little clunky but it keeps the mappings section cleaner at least

Yeah, I've realized we need to revamp extension setup a bit upstream to make this use case a bit more simple. I think we can also get rid of `require "telescope".load_extension "file_browser"` if we do it properly.

> Still learning Lua, but it seems like require'pkg' can be side-effectful? And if you evaluate that expression multiple times, will it initialize things multiple times?

AFAIK, lua caches `require`. This shouldn't be so much of an issue here, it's just that the telescope extension framework is written in a way that the extension setup is only called once on the first access of the `require "telescope".extension.$EXTENSION` table. I guess you could call afterwards with a hidden API once more, but this is not user friendly.

In any case, telescope's plan is to move pickers out of core incrementally (and the file-browser being a primary case), we need to polish that extension system.

Apologies, you'll have to live with the work-around for a bit, while fixing the upstream in a simple PR is easy, the general API needs a bit of a cleaner redesign.

**Comment by j-hui** [comment]
Got it, thanks! I can just stick with my current workaround, and am happy to close this issue for now.

> Don't think you have to wrap it in tbl_extend force, no?

I'm not sure if this is intentional upstream, but I first started doing this because I noticed that my global mappings were being overridden by extension-specific mappings when I was trying out the built-in file browser. That is, default globals < user globals < default extension < user extension. (Is that correct?)

My tbl_extend force makes it such that my own mappings are also being declared as extension-specific mappings, so that they take the highest priority.

**Comment by fdschmidt93** [comment]
I think for the time being, this PR is a strict improvement wrt the mappings situation. Maybe if the upstream mappings PR is merged, we'll have to change something, but that may or may not take some more time.

Hopefully no breakages for users, my testing (and `actions.which_key`) indicate that by default everything works as intended.

Slight breaking change: `fb_actions.goto_prev_dir` has now been renamed to `fb_actions.goto_parent_dir`

**Pull request merged**
