### PR TITLE
feat: create file from prompt + create fixes

### PR DESCRIPTION
**Pull request by fdschmidt93**
This PR introduces the `fb_actions.create_from_prompt` which allows to create files or folder from prompt and directly open them via `telescope-file-browser.nvim` (i.e. if you open a folder, you'll land in that folder).

Creds to @otavioschwanck for the original idea and implementation :)

Furthermore, this commit reflects a breaking change. The input callback to create a file or folder via the prompt if no result is shown is now superseded by the `fb_actions.create_from_prompt` mapped by default to Shift-CR (works if your terminal recognizes this, otherwise please remap).

cc @danielnehrig @ZhiyuanLck as you might have used that feature

Please don't be too concerned with the default mapping; once some previewer upstream refactoring etc is committed, I plan to reconsider mappings and disseminate info about recent file browser updates on reddit to draw attention to a wider audience.

### CODE REVIEW

**Comment by danielnehrig** [comment]
might it not make sens to make the default behaviour something else then `<S-CR> pressing shift+cr does nothing for me probably as you mentioned i have to set some thing in my kitty conf

**Comment by otavioschwanck** [comment]
> might it not make sens to make the default behaviour something else then ` pressing shift+cr does nothing for me probably as you mentioned i have to set some thing in my kitty conf

i remapped to Ctrl + space on my config.

**Comment by otavioschwanck** [comment]
> > might it not make sens to make the default behaviour something else then ` pressing shift+cr does nothing for me probably as you mentioned i have to set some thing in my kitty conf
> 
> i remapped to Ctrl + space on my config.  Would be nice to have something like that by default

**Comment by fdschmidt93** [comment]
> Please don't be too concerned with the default mapping; once some previewer upstream refactoring etc is committed, I plan to reconsider mappings and disseminate info about recent file browser updates on reddit to draw attention to a wider audience.

Please understand I won't introduce a single mapping breaking change to a perfectly logical mapping that for some reason does not work for you. As per above, mappings as a whole will be reviewed eventually. Remapping is for good reason very easy -- we won't be able to please everyone, since there are so many mappings in the file browser.

**Pull request merged**
